server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true # 向 Eureak server 注册
    fetch-registry: true # 从 server 获取其他微服务注册信息
    service-url:
#      defaultZone: http://localhost:7001/eureka
      # 微服务注册到 Eureak 集群
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka