server:
  port: 80

eureka:
  client:
    register-with-eureka: false # Feign 客户端不需要注册到 Eureka
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka # 单机测试
